name: Unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  tests:
    name: Run unit tests
    runs-on: temurin-18-lein-alpine
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - run: |
          lein test
